### PR TITLE
Add a command to create the recent apps stack

### PR DESCRIPTION
**Pull request by Hummer12007**
Added a command to create a stack (in Dock) with most recently launched apps, and a new section for it.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks. Now please resolve the conflicts and push again so I can merge.

**Comment by herrbischoff** [comment]
Are you going to update this pull request or should I close it?

**Comment by Hummer12007** [comment]
Sorry, I was rather busy this week. Will update ASAP

**Comment by herrbischoff** [comment]
Just a quick reminder that pull requests that haven't changed in 7 days will be closed.

**Pull request closed without merging**
