### PR TITLE
Added Upterm to the list of alternative terminal apps.

### PR DESCRIPTION
**Pull request by airportextreme**
From Upterm project page: Upterm (formerly Black Screen) is an IDE in the world of terminals. Strictly speaking, it's both a terminal emulator and an interactive shell based on Electron.

I am not affiliated with Upterm.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Same as over at https://github.com/iCHAIT/awesome-macOS: why do you assume no one else has already come up with the idea? You need to search previous pull requests before you submit: https://github.com/herrbischoff/awesome-osx-command-line/pull/121

**Comment by airportextreme** [comment]
If you look at my profile, you will see that I'm pretty new to this, but since it's not fun at all, I'm done.

**Comment by airportextreme** [comment]
By the way, even if I had searched for Upterm, it wouldn't have come up because as you noted, it had changed names since the last related pull request, but I'm glad I gave you an opportunity to show us all how much smarter you are.

**Comment by herrbischoff** [comment]
Thinking for yourself really does help. As you yourself put it in the description:

> Upterm (formerly Black Screen)

Soooo... I suppose taking the 5 seconds it takes to search for both names is too much to ask but making me do the work is not?

**Comment by airportextreme** [comment]
Again, I am so sorry to have wasted your very important time. I will not do so again.

**Pull request closed without merging**
