### PR TITLE
Add top - an Activity Monitor for the Terminal

### PR DESCRIPTION
**Pull request by alan707**
`top` is a sorted list of System Processes.  Similar to Activity Monitor but displays processes on the terminal.

### CODE REVIEW

**Comment by laughedelic** [comment]
IMO `top` is not a good fit for this list. It's a standard unix tool and is not something awesome or specific for OS X command line.

**Comment by alan707** [comment]
I actually have a second PR for `htop` which I think is much better than top.  Since this is my first contribution, I wanted to dip a toe first.
> IMO top is not a good fit for this list. It's a standard unix tool and is not something awesome or specific for OS X command line.
I figured since `ping`, `find`, or `shutdown` are on this list, something as useful as seeing all your memory hugry processes, would be a nice find for many command line fans.

**Comment by herrbischoff** [comment]
I would argue that `top` is not a bare-bones-absolutely-necessary tool to get around. You're on a Mac, therefore you have `Activity Monitor.app`. Adding it would open the door for the next person to feel that her/his favorite standard unix tool should be added as well. Low-hanging fruit for pull requests, you know.

**Comment by alan707** [comment]
got it!

**Pull request closed without merging**
