### PR TITLE
Add commands to cleanup trash and .DS_Store files

### PR DESCRIPTION
**Pull request by tricinel**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for your suggestion. This is a little bit too much thrown together for my taste. Please make the "Empty Trash" command separate from the system log deletion. I would not expect my system logs to be wiped by a trash cleanup.

Also, the Metadata delete command is a duplicate.

**Comment by tricinel** [comment]
Ouch, sorry, yeah the Metadata delete was there. I expected to find it in the Metadata not in Find category though :) Do you want me to remove my addition or does it make sense to have it in the Metadata instead of the Find category?

Splitting that Trash command though, you're right.

**Comment by tricinel** [comment]
Done.

**Comment by herrbischoff** [comment]
Thanks. Now please rebase your clone with the new additions so there are no more merge conflicts and I can merge.

**Comment by tricinel** [comment]
There's actually a lot of conflicts, the rebase fails. I can however fetch and merge then push.

**Comment by herrbischoff** [comment]
I see you worked on the master branch, which is almost always a bad idea. The easiest way would be to close this pull request, delete the clone directory and start fresh. Always work in a branch to avoid these kinds of rebase issues. Master needs to be clean at all times.

**Pull request closed without merging**
