### PR TITLE
Adding Open command section

### PR DESCRIPTION
**Pull request by willywos**
Hello!

I thought it might be good to share the open command on the list because it's one of those commands that new people don't really know and once they do they use it all the time. There are examples for opening a url, file, application and a directory.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Good idea! Since they are primarily Finder-related, I would put them as a sub-category there. Please move them there and I will merge.

**Comment by willywos** [comment]
There you go! 

Thanks for creating this list @herrbischoff

**Comment by herrbischoff** [comment]
Great! Now the titles need to be [properly capitalized](https://github.com/herrbischoff/awesome-osx-command-line/blob/master/contributing.md), to keep things tidy. ;) Missed that the first time around.

**Comment by willywos** [comment]
Titles have been capitalized.

**Comment by herrbischoff** [comment]
Looks good! Merging now.

**Comment by willywos** [comment]
:tada: :tada:  

Thanks!

**Pull request merged**
