### PR TITLE
Stop Itunes from Responding to the Keyboard Media Keys

### PR DESCRIPTION
**Pull request by vinkla**
Make iTunes ignore users pressing the media keys.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Additionally, running the command in 10.11 gives the following error:
```
/System/Library/LaunchAgents/com.apple.rcd.plist: Could not find specified service
```

**Comment by G07cha** [comment]
@herrbischoff, it's ok becouse you already unloaded service, if you will load service back and try unload again, it will unload without any message, if you unload second time it will give you same message as you accrued.
Btw, I'm think that redirect to `/dev/null` is unnecessary too

**Comment by vinkla** [comment]
Okay, I've removed `/dev/null`.

**Comment by herrbischoff** [comment]
@G07cha: Thanks, I thought as much. I should really get more sleep. ;)

@vinkla: Thanks. Merging.

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
