### PR TITLE
Add HyperTerm and Black Screen as Terminal alternatives

### PR DESCRIPTION
**Pull request by MatthiasWinkelmann**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thank you for your suggestion. I was thinking about adding them a while back but did not, for the time being.

Do you feel that any of them is ready for prime time usage? It appears to me that those are at best early beta versions with a lot of work still to be done. Terminal.app itself is probably more capable than any of them. The idea of a HTML/CSS/JS-based terminal emulator is kind of intriguing but as of right now doesn't feel quite right to me. I'm absolutely open to arguments and to learn something new, so feel free to let me know what you think.

**Comment by MatthiasWinkelmann** [comment]
HyperTerm is useable (I've switched) but after trying Black Screen again I have to agree with you. I've also just discovered that Terminal.app has changed quite a bit from the last time I tried it.

Soo... feel free to close the PR or keep it around and merge it a few month. Thx for the excellent ressourcce!

**Comment by herrbischoff** [comment]
Thanks for your feedback. I'm going to keep this open and check back in a couple of months if they improved noticeably.

**Comment by herrbischoff** [comment]
As no significant progress has been made since August, I'm going to close this issue for now. We may revisit at a much later time, after HyperTerm and Black Screen have both pushed out a 1.0 version (currently at 0.8.3 and 0.2.79 respectively). I for one wouldn't call any of those terminal apps "awesome" as of now (and for the foreseeable future).

Additionally, I *really, really, really* dislike Electron wrappers, aka bundled web apps.

**Comment by herrbischoff** [comment]
Black Screen is now called Upterm but nothing has changed regarding performance and feature set. As there has been a recent [duplicate pull request](https://github.com/herrbischoff/awesome-osx-command-line/pull/178), I'm going to shut this down permanently.

**Pull request closed without merging**
