### PR TITLE
Add "Show Current SSID"

### PR DESCRIPTION
**Pull request by rileyjshaw**
Pretty useful when combined with "Show Wi-Fi Network Passwords" :)

### CODE REVIEW

**Comment by herrbischoff** [comment]
Cool! :) So we can run one humongous command:

```
security find-generic-password -a "$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}')" -gw
```

Or, combined with the shortcut above, short and sweet:

```
security find-generic-password -a "$(airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}')" -gw
```

The power of the command line shell.

Please do sort correctly though and I will merge.

**Comment by rileyjshaw** [comment]
> Order titles alphabetically within each category.

Gah, I totally missed that in the contribution guidelines! Sorry about that, fixing now.

**Comment by rileyjshaw** [comment]
Alright, fixed the order

**Comment by herrbischoff** [comment]
No problem. Looks good now! Merging.
And for today, I'm going off to bed. In case you submit more pull requests. ;)

**Comment by rileyjshaw** [comment]
Heh, alright – good night!

**Pull request merged**
