### PR TITLE
List All Apps Downloaded from App Store

### PR DESCRIPTION
**Pull request by dcondrey**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for the shorter command. But why delete the `find` command? It still works — and even would if someone turned off Spotlight indexing. Please change to a format that both commands are included. Like:

```
# Via find
...

# Via Spotlight
...
```

**Comment by dcondrey** [comment]
Updated as requested.

**Comment by herrbischoff** [comment]
Thanks!

**Comment by jdickey** [comment]
Another alternative people may want to consider is [`mas`](https://github.com/mas-cli/mas) by @argon and team.

Once `mas` is installed, `mas list` will list all application installed from the App Store in formatted columns for app ID number and app name/version. You can, for example, create this file on a system where you've signed into the App Store with

```
$ mas list | cut -d ' ' -f 1 > mas-list.txt
# schlep file to new or newly-reimaged Mac
$ for i in `cat mas-list.txt`; do
> mas install $i
> done
# ...applications install...
$
```

That snippet is now part of my standard "get-a-clean-system-up" script.

**Pull request merged**
