### PR TITLE
Add Login Window Text

### PR DESCRIPTION
**Pull request by gillstrom**
This sets a text on the login window.

If you want me to place it in any other way I'll fix it.

### CODE REVIEW

**Comment by vinkla** [comment]
:+1:

**Comment by herrbischoff** [comment]
Excellent addition, but please change it so it reads "Login Window" in all places.

**Comment by gillstrom** [comment]
It should now say `Login Window` everywhere!

**Comment by herrbischoff** [comment]
Great, thanks! Merged.

**Pull request merged**
