### PR TITLE
add function to open man pages in Dash.app

### PR DESCRIPTION
**Pull request by boneskull**
this may be a little too involved, but let me know what you think.  it's pretty cool!

### CODE REVIEW

**Comment by herrbischoff** [comment]
I'm conflicted. While surely an interesting solution, it's very specific to Dash.app and not a simple plist change. I don't want this list to get too bloated with all kinds of scripts. Comments anyone?

**Comment by G07cha** [comment]
I agree, it's too specific

**Comment by boneskull** [comment]
very well.  [gist](https://gist.github.com/boneskull/4b6378784e2d719dd543)

**Comment by herrbischoff** [comment]
I have just had an idea on how to collect all those useful things. Please see issue #35 and let me know what you think. Thanks.

**Pull request closed without merging**
