### PR TITLE
Turn on/off "Auto rearrange Spaces based on most recent use"

### PR DESCRIPTION
**Pull request by mhumeSF**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thank you very much for your submission.

Please format your entry according to the rules specified in [contributing.md](https://github.com/herrbischoff/awesome-osx-command-line/blob/master/contributing.md), especially with regard to capitalization.

**Comment by herrbischoff** [comment]
Thanks, I had to clean it up a bit to merge it.

**Comment by mhumeSF** [comment]
Gah, yea sorry. I did see that, but you beat me to it.

**Comment by herrbischoff** [comment]
I really would have liked to give you proper credit but resolving merge conflicts on the command line apparently won't honor the original authors' id.

**Pull request closed without merging**
