### PR TITLE
Add awesome bot for links

### PR DESCRIPTION
**Pull request by vinkla**
Read more about the awesome bot here https://github.com/dkhamsing/awesome_bot

Maybe we should close the other pull request for tests?

### CODE REVIEW

**Comment by vinkla** [comment]
The awesome BOT found 4 issues:

```sh
Issues :-(
> Links 
  1. 301 http://www.github.com → https://www.github.com/
  2. http://su.example.com:8088/index.sucatalog getaddrinfo: Name or service not known
  3. 301 https://i.creativecommons.org/l/by-sa/4.0/88x31.png → https://licensebuttons.net/l/by-sa/4.0/88x31.png
  4. http://www.hawkwings.net/2007/03/03/scripts-to-automate-the-mailapp-envelope-speed-trick/ getaddrinfo: Temporary failure in name resolution
```

**Comment by herrbischoff** [comment]
Nice! Thanks for the suggestion and changes. I'm all for it. Let's whitelist the link from the script though, as it's an attribution and the site may come online again. Also, closing the other testing pull request is a good idea as `awesome_bot` seems to be exactly what we're looking for.

**Comment by vinkla** [comment]
Okay, all fixed.

**Comment by herrbischoff** [comment]
Good stuff. I'm just going to pull the trigger here and hope it works as expected... :D

**Comment by vinkla** [comment]
Thanks! It should work. I use it myself in https://github.com/vinkla/awesome-fuse without any issues.

**Comment by vinkla** [comment]
I guess we can delete the `setup-files` branch as well?

**Comment by herrbischoff** [comment]
Yup, just do away with it.

**Comment by vinkla** [comment]
Do you want me to remove it or will you?

**Comment by herrbischoff** [comment]
I'll leave the honors to you. ;)

**Comment by vinkla** [comment]
Thanks :)

**Pull request merged**
