### PR TITLE
Add "cd to the Folder Currently Open in Finder"

### PR DESCRIPTION
**Pull request by rileyjshaw**
If multiple windows are open, it chooses the top-most one.

### CODE REVIEW

**Comment by herrbischoff** [comment]
See inline comment. Nice addition though!

**Comment by rileyjshaw** [comment]
@herrbischoff good call, updated the title :)

**Comment by herrbischoff** [comment]
Thanks. Now just sort properly and I will merge.

**Comment by rileyjshaw** [comment]
Done.

**Comment by herrbischoff** [comment]
Thanks!

**Pull request merged**
