### PR TITLE
Add `nettop` command

### PR DESCRIPTION
**Pull request by caillou**
The `nettop` program displays a list of sockets or routes. The counts for network structures are updated periodically.

Very useful if you want to know which program uses what socket.

### CODE REVIEW

**Comment by binhnguyen1512** [comment]
```nettop

**Comment by herrbischoff** [comment]
Thank you very much for your submission.

Please format your entry according to the rules specified in [contributing.md](https://github.com/herrbischoff/awesome-osx-command-line/blob/master/contributing.md), especially with regard to capitalization.

**Comment by caillou** [comment]
@herrbischoff Title has been capitalized.

**Comment by caillou** [comment]
Seems not wanted. Closing.

**Pull request closed without merging**
