### PR TITLE
Added a hack to disable icons bounce alert

### PR DESCRIPTION
**Pull request by f213**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Please see my inline comment.

**Comment by f213** [comment]
Here it is!

**Comment by herrbischoff** [comment]
Please don't be sloppy. It should be formatted like the other entries, including a "disable" and "enable" part. Look at the whole file and adhere to the style.

**Comment by herrbischoff** [comment]
Why did you close the pull request? Are you going to submit a new, correct one?

**Comment by herrbischoff** [comment]
Nevermind, I just added it myself: https://github.com/herrbischoff/awesome-osx-command-line/commit/ccf49bf24d8ed65fd4020339e68a56fed287ab0b

**Pull request closed without merging**
