### PR TITLE
Update link to community version of prezto

### PR DESCRIPTION
**Pull request by dritter**
sorin-iconescu/prezto is abandoned, see https://github.com/sorin-ionescu/prezto/issues/1239 the project moved to https://github.com/zsh-users/prezto

### CODE REVIEW

**Comment by herrbischoff** [comment]
I see recent commits in the original repo from February and March, so this does not seem to be abandoned. Given the popularity of the source, I don't see a reason to link to a very young fork.

Maybe @sorin-ionescu himself can shed some light on this. If he's on board with the new community fork, I will merge this.

**Comment by dritter** [comment]
> I see recent commits in the original repo from February and March, so this does not seem to be abandoned. Given the popularity of the source, I don't see a reason to link to a very young fork.

Yep. 2016.. Anyway. Your decision. Just wanted to let you know.

And I don't think Sorin will answer here or join there. He didn't answer on the thread I mentioned (and which is about moving Prezto to the more official "zsh-users").

**Comment by paulmelnikow** [comment]
Would like to see this get merged!

**Comment by herrbischoff** [comment]
I'm going to give @sorin-ionescu until the end of the month to reply with a short comment on the current state of his project. If there is no word from him, the community fork will will added in its place.

**Comment by paulmelnikow** [comment]
You could list both in the meantime. Would you be open to that?

**Comment by antoineco** [comment]
@paulmelnikow why would that be relevant? Does any external project depend on that link being updated?

The author responded to the thread mentioned earlier, let's see if he wants to continue maintaining the project or not.

**Comment by herrbischoff** [comment]
Exactly. Especially his mentioning of not even having received an email is worrying. Is the social media notification craze already at a point where people can't be bothered to write a single email any more? Real life interferes with the best of plans.

I'm just going to wait until the situation resolves itself. I bet they will all just merge everything back into the original repo and continue from there with several contributors.

**Comment by sorin-ionescu** [comment]
Prezto is not abandoned, but it has been neglected publically for a year. I want to give write access to several volunteers. There are several forks, which need to be reconciled.

A GitHub notification subject line starts with `[user/repository]`, which often does not even fit in the threads column row of an email client, for example `Re: [herrbischoff/awesome-osx-command-li...`, let alone the issue title. I have hundreds of notification threads on Prezto alone. So, using GitHub notifications to get a hold of someone's attention is not effective. I wish @facastagnini or someone else that commented in https://github.com/sorin-ionescu/prezto/issues/1239 had sent me an email.

**Comment by herrbischoff** [comment]
Thanks for your comment, @sorin-ionescu. That's what I figured. The sheer amount of notifications the sole maintainer of a popular open source project gets is staggering. If Real Life™ issues of any kind take the focus away for some time, getting back on top is almost impossible.

I view this as resolved and will leave the original repo in place as in all likelihood the changes made in other forks will be merged back into it with the help of additional volunteers.

**Comment by dritter** [comment]
Chapeau to your gut feeling @herrbischoff 

And good to see you around again @sorin-ionescu

**Pull request closed without merging**
