### PR TITLE
Show IP Address

### PR DESCRIPTION
**Pull request by vinkla**
Don't know about the naming/description though. Any thoughts to make it better?

### CODE REVIEW

**Comment by G07cha** [comment]
What about "Show public IP address" title?

**Comment by vinkla** [comment]
@G07cha That might be better, what do you think @herrbischoff?

**Comment by herrbischoff** [comment]
I'd call this "Show External IP Address".

**Comment by herrbischoff** [comment]
Also, please move this and #20 to the TCP/IP category. Just because every Mac sold nowadays has Wi-Fi does not make it the only way to connect to a network... ;P

**Comment by vinkla** [comment]
All fixed :)

**Comment by herrbischoff** [comment]
Thanks. Merging.

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
