### PR TITLE
Add a command for burning ISO to DVD

### PR DESCRIPTION
**Pull request by deanboole**
Made some changes according to the contributing.md.

However, I'm not sure about putting this command in the category of Disk Images.
Any other suggestions?

Thanks.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for your addition. As this command is applicable for all kinds of disk images, it would be better to name it accordingly. In a short description mention that it also applies to .iso and .img images.

**Comment by deanboole** [comment]
Thank you for the suggestion.

I read this https://en.wikipedia.org/wiki/Apple_Disk_Image.
And added short description mention that it also applies to images (Yes, I named it accordingly.)  :-D

**Comment by herrbischoff** [comment]
Thanks for the change. However, AFAIK there are no .fat, .hfs, .smi or .udf images. Those are types and filesystems housed in the .iso, .img and .dmg file formats.

**Comment by deanboole** [comment]
Oh! I'm sorry for not reading the document carefully.

So what I'm gonna do is to change the short description to:
>`This command applies to .iso, .ing and .dmg images.`

If the short description is correct, I'll then update the README.md file.

Thank you for pointing out my mistakes.

**Comment by herrbischoff** [comment]
Sounds good. Just write `.img` instead of `.ing` and we're golden. :)

**Comment by herrbischoff** [comment]
Merged by other means.

**Comment by deanboole** [comment]
Thank you :smiley:

**Pull request closed without merging**
