### PR TITLE
Added Full Keyboard Access

### PR DESCRIPTION
**Pull request by ogzolmz**
Hi,
I added "Full Keyboard Access" to Keyboard section.
best regards.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Nice! Please sort alphabetically inside the section and I will merge this.

**Comment by herrbischoff** [comment]
Sorry, this was not formatted very well, so I went ahead and added the two relevant settings manually. Thanks again for suggesting it!

**Comment by ogzolmz** [comment]
You are welcome

**Comment by herrbischoff** [comment]
For good measure, I have amended the commit to reflect you being the author: https://github.com/herrbischoff/awesome-osx-command-line/commit/80c5b9d7fbd29f698c183fa7881eb028728b549b

**Pull request closed without merging**
