### PR TITLE
Add Prezto link to Zsh section

### PR DESCRIPTION
**Pull request by Glutnix**
Prezto is a faster framework than Zsh. It's worthy of mentioning.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for the recommendation. As far as I can see, it appears to be quite limited and not really well documented. Did I miss something?

**Comment by Glutnix** [comment]
I'm probably not the right guy to defend Prezto vs OhMyZsh, but I'd say Prezto is not as flexible or extensible as OMZ, but it still brings a lot of that Zsh power to play without the slowdown. It's still got a lot of what I would guess the majority of people use OMZ for.

**Comment by Glutnix** [comment]
As for documentation, yeah, the project is lacking, but there are many good posts on other sites detailing it.

**Comment by herrbischoff** [comment]
Could you give me some links to check out?

**Comment by Glutnix** [comment]
* http://codurance.com/2015/03/16/installing-zprezto-a-quick-guide/
* http://jeromedalbert.com/migrate-from-oh-my-zsh-to-prezto/
* http://mikebuss.com/2014/04/07/customizing-prezto/
* http://joshsymonds.com/blog/2014/06/12/shell-awesomeness-with-prezto/
* http://concreted.azurewebsites.net/custom-terminal-with-zshell-iterm-and-prezto/ (dated 3 Nov 2014)

**Comment by herrbischoff** [comment]
Thanks, I'm going to check them out and let you know.

**Comment by herrbischoff** [comment]
Thanks again for your suggestion. I had the opportunity today to check it out. I'm pretty impressed by it's snappiness. I'm possibly becoming a convert. ;)

Anyway, I'm merging. I can see how this would be useful to others as well.

**Comment by herrbischoff** [comment]
Addition: yes, I'm a convert. :) Prezto is a winner in my book. The `rm` alias was driving me nuts though...

**Comment by Glutnix** [comment]
Agreed about the `rm -i` alias, but I'm more of a [trash](http://hasseg.org/trash/) fan. I could do that as another pull request.

**Comment by herrbischoff** [comment]
Interesting. But where would it go? And personally, I like things to get deleted right away. ;)

**Pull request merged**
