### PR TITLE
add a simple menu, ease of use

### PR DESCRIPTION
**Pull request by qihaiyan**
call the menu: 
```shell
sh msh.sh
```
screen:
default

A menuItem with a star means it's execuable, others are parent menu.
The menu is defined in msh.etc, and the corresponding function is defined in msh.fun.
Adding new menu or changing is very easy.

### CODE REVIEW

**Comment by herrbischoff** [comment]
This is intriguing, thank you! :)

In the spirit of DRY: how about a function that is updating the script's content automatically? This is probably not possible in plain shell script as you would need to convert from Markdown to plain text. I don't see manually updating for every change happening. This would effectively be duplicating data and amounts to tedious work.

**Comment by herrbischoff** [comment]
Although: https://github.com/chadbraunduin/markdown.bash

**Comment by qihaiyan** [comment]
1. Gennerate shell script from Markdown.
It's not easy because the README.md is not that structured.
2. Generate Markdown from the shell content.
It's possible, if you agree with it, i'll give it a try with https://github.com/chadbraunduin/markdown.bash.

**Comment by herrbischoff** [comment]
As I don't see this as feasible to support in the long run, I'm going to close the pull request. I don't want to discourage you, however the added maintenance and additional barrier of contributing will almost certainly not be worth it. This appears to be one of those ideas that sound neat in theory until you think through the long-term implications.

**Pull request closed without merging**
