### PR TITLE
Add basic travis config (WIP)

### LINKED ISSUE #43: Travis integration
Create a `.travis.yml` file that runs test on all included bash scripts along with the alias and function files.

### PR DESCRIPTION
**Pull request by vinkla**
This is the work in progress pull request to add Travis support.

This closes #43

### CODE REVIEW

**Comment by vinkla** [comment]
@herrbischoff I don't know which setup we want to use but in this PR we test the `setup.sh` script and see how well it performs on OS X 10.9, 10.10 and 10.11. Let me know what you think about this.

**Comment by herrbischoff** [comment]
@vinkla: Nice work. I'm wondering though why the badge still shows that the build is failing although it is passing.

Apart from that little hiccup, I think we should test both at least `setup.sh`, `brew.sh` and the sourcing of the `aliases` and `function` files. If all of them go smoothly, this would account for the most basic code glitches like missing colons, quotes and the like. It would also make sure that all Homebrew formulas are available and installing correctly.

I suppose you removed the pre-sudo check because Travis would otherwise complain, correct?

This automation is going to be a treat when finally set up. ;)

**Comment by vinkla** [comment]
@herrbischoff The reason it show failing is because I pointed it against the `master` branch.

**Comment by vinkla** [comment]
Why should we test the other files? Isn't it better we just test all snippets?

**Comment by herrbischoff** [comment]
Well, I believe that as long as we're testing, we could as well test the whole bunch for code problems. That's my thinking. Any reason why we shouldn't?

**Comment by vinkla** [comment]
Maybe we should but I don't agree we should use similar setup to Mathias Bynens dotfiles. IMO I think we should only create a script which executes all the snippets from the README. We don't provide dotfiles like in Mathias project.

What is your opinion on this?

**Comment by herrbischoff** [comment]
Ahh, now I see what you mean. Sure, that could be a way. I thought that by adding extra files that would be a place to put all the nice functions and solutions people come up with without cluttering the main list. Kind of an expanded version of the list, for inspiration and copy and paste.

A single script testing the main README would of course ease the burden of having to put stuff in several places. Well...

Okay, agreed. For now we stick with the main list. Are you going to take a stab at the script iterating through the commands or should I?

**Comment by vinkla** [comment]
Okay, cool. For me it works either way, maybe it is better if you do it? Since you seem to know all about the awesome terminal stuff. I can help but I think it will become better if you do. Thats okay with you?

**Comment by herrbischoff** [comment]
Sure, I'm going for it. ;)

**Comment by vinkla** [comment]
:+1:

**Comment by herrbischoff** [comment]
Okay, I let my `sed`-fu out and cooked something up along the lines of:

```
sed -n '/^```bash/,/^```/p' < README.md | sed '/^```/d' | sed ':a;N;$!ba;s/\&\& \\\n/\&\& /g'
```

:D

This gets everything every command out as a single line which we can then run through a `for` loop. However, commands that require, for example, a disk image will have none. We can either create simple test files and put them in a `test` folder or need to think of a way to skip those. Additionally, commands like restarting the system and unlocking FileVault automatically would very likely put Travis either in an infinite testing loop or simply fail every time.

Any thoughts on this?

**Comment by herrbischoff** [comment]
Added the whole contraption. Somehow one clipboard command refuses to play along. I'll have to look into it later.

**Comment by vinkla** [comment]
Actually I've no idea how rebooting system and FileVault will work on Travis. I guess it could be hard to get it to pass. Then again, I don't know. We'll have to test :)

Maybe we should point the travis against the new `test.sh` file? I can do that if you want?

**Comment by vinkla** [comment]
Any progress on this?

**Comment by vinkla** [comment]
Closing in favour of #102

**Pull request closed without merging**
