### PR TITLE
add LaunchAgent which periodically upgrades homebrew

### PR DESCRIPTION
**Pull request by boneskull**
suggestions welcome, thanks!

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for your suggestion. Although nice, I feel this is a little too specific to Homebrew to be included in this list. I'll leave this open for the time being to give others the opportunity to comment. If there is enough interest, I may expand the Package Managers category. Still, I'd see this better placed in a Gist that is linked to.

**Comment by plessbd** [comment]
what about making it the example for doing the periodic job, fills two roles, allowing people to see how to run the periodic job as well as giving a practical example

**Comment by herrbischoff** [comment]
@plessbd: Intriguing idea. Let me sleep on it.

**Comment by G07cha** [comment]
+1 for link to Gist.

**Comment by boneskull** [comment]
Where would I put the link?

**Comment by G07cha** [comment]
@boneskull, good question, my opinion is to set link with short description, like:
`[.plist file](https://gist.github.com/your-gist)`
But @herrbischoff may have different opinion so let's wait for him.

**Comment by herrbischoff** [comment]
I would either favor the default template idea, explaining a little more what's going on in the file or using it in a collection of system defaults like proposed in #35. Let me know what you think!

**Comment by d6rkaiz** [comment]
Hi,
the links that are included in this PR could not be resolve.

```
$ curl -I http://curvve-curvvemedia.netdna-ssl.com/wp-content/uploads/2013/09/homebrew_osx_logo.png
curl: (6) Couldn't resolve host 'curvve-curvvemedia.netdna-ssl.com'
```

Correct link is this?
http://cdn.curvve.com/wp-content/uploads/2013/09/homebrew_osx_logo.png

**Comment by herrbischoff** [comment]
Confirmed. The link does not resolve. The replacement link does however.

**Comment by herrbischoff** [comment]
To finally resolve this long-running PR, I have decided with 479cd58 to add a new file `launchagents.md` and put the submission (along with the correct image link) in there. I have also done the same for functions. It would be a shame for the good and creative ideas to go to waste, so feel free to contribute in those files. This should keep things neat and tidy while still being comprehensive and useful.

@boneskull: If you're interested, I can delete the entry so you can re-add it for proper attribution. Let me know.

**Comment by boneskull** [comment]
@herrbischoff not necessary. thanks!

**Pull request closed without merging**
