### PR TITLE
Increase Number of Recent Places

### PR DESCRIPTION
**Pull request by vinkla**
Reference https://gist.github.com/wesbos/f38ce56002292db71a82

### CODE REVIEW

**Comment by vinkla** [comment]
What do you like the `snippet` label? Maybe there is a better name …

**Comment by herrbischoff** [comment]
Please see my inline comment. Other than that, I believe a new label is not necessary, as most of these additions are snippets in one way or the other.

**Comment by vinkla** [comment]
Okay, I'll remove it.

**Comment by vinkla** [comment]
Done.

**Comment by herrbischoff** [comment]
Great! Merged. Thanks.

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
