### PR TITLE
Added command to launch screen saver

### PR DESCRIPTION
**Pull request by janost**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Nice addition! Please see my inline comment.

**Comment by janost** [comment]
Thanks for the review. Your suggestion has been applied.

**Comment by herrbischoff** [comment]
Now just [sort the entry correctly](https://github.com/herrbischoff/awesome-osx-command-line/blob/master/contributing.md) in its category and I will merge.

**Comment by janost** [comment]
Apologies for missing that. Fixed.

**Comment by herrbischoff** [comment]
Thanks! Merged.

**Pull request merged**
