### PR TITLE
Space to Dock command

### PR DESCRIPTION
**Pull request by vladmrnv**
Added a command to add a space in your dock

### CODE REVIEW

**Comment by herrbischoff** [comment]
Thanks for your suggestion. Please see my inline comments.

**Comment by vladmrnv** [comment]
I'm still trying to learn how to properly do pull requests, please let me know if I did it correctly, thank you.

**Comment by herrbischoff** [comment]
It's all good! :) And don't worry, we all learn something new every day. Merged.

**Comment by vladmrnv** [comment]
Thank you, Ill keep your suggestions in mind next time I try to work on something.

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
